AppID = "MabelMedia-LLC.QuicBuild"
ShortDescription = "Building Rust Programs, Made Simple."
LongDescription = ["QuicBuild Removes All The Fuss About:", "- The Annoying Target Folder Structure", "- Shell Flags", "- And Massive Default Binary Sizes", "", "QuicBuild Solves All These Problems, And Provides UPX Integration (UPX Installation Required) To Compress Your Binaries Further."]
FileBundleHashes = ["b774a3fdd834d380f3e7793c588f3e34a57864231623c765d1cc2cbe1773870b", "dea2867786a5a0d781eb5ab90517ac2666282600be60065a65dfe3e2959b4d77", "c72a59616415739d0d6f0a5e5b85c662e907cb3c415f0bdd65c7549a7287598f"]

[Version]
Major = 0
Minor = 2
Patch = 7
BuildNumber = 271

[MainExec]
Linux = "QuicBuild"
MacOS = "QuicBuild"
Windows = "QuicBuild.exe"
