AppID = "MabelMedia-LLC.QuicBuild"
ShortDescription = "Building Rust Programs, Made Simple."
LongDescription = ["QuicBuild Removes All The Fuss About:", "- The Annoying Target Folder Structure", "- Shell Flags", "- And Massive Default Binary Sizes", "", "QuicBuild Solves All These Problems, And Provides UPX Integration (UPX Installation Required) To Compress Your Binaries Further."]
FileBundleHashes = ["a428163601e987fade32efefa04e285e80b50a41c88d7b822b555a487b45b7a0", "0389446128766dd55ae6db06a751216e54ec866b82618ca1d7a7fda45e0ee921", "b17ebea451b001c40e5cb52304611d7520eb9e0068ff3b8663495060d1661402"]

[Version]
Major = 0
Minor = 2
Patch = 7
BuildNumber = 271

[MainExec]
Linux = "QuicBuild"
MacOS = "QuicBuild"
Windows = "QuicBuild.exe"
