ManifestVersion = 1
AppID = "MabelMedia-LLC.QuicBuild"
ShortDescription = "Building Rust Programs, Made Simple."
LongDescription = ["QuicBuild Removes All The Fuss About:", "-The Annoying Target Folder Structure", "-Shell Flags", "- And Massive Default Binary Sizes", "", "QuicBuild Solves All These Problems, And Provides UPX Integration (UPX Installation Required) To Compress Your Binaries Futher."]

[Version]
Major = 0
Minor = 2
Build = 0

[MainExec]
Linux = "QuicBuild"
MacOS = "QuicBuild"
Windows = "QuicBuild.exe"
