AppID = "MabelMedia-LLC.QuicBuild"
ShortDescription = "Building Rust Programs, Made Simple."
LongDescription = ["QuicBuild Removes All The Fuss About:", "-The Annoying Target Folder Structure", "-Shell Flags", "- And Massive Default Binary Sizes", "", "QuicBuild Solves All These Problems, And Provides UPX Integration (UPX Installation Required) To Compress Your Binaries Futher."]
FileBundleHashes = ["d65506db4896d9e03595bd35e04c529d4c0f4a3da1b9aca71835a6741ffc8d31", "15912a6f093fa5a7404859f78a0ef43fcdbf42cd286607044f99c99cbac93947", "abc501e5d308cec8e69d457362ceda8dee400e5702d5f3f91a68b8be37d116bb"]

[Version]
Major = 0
Minor = 2
Patch = 6
BuildNumber = 262

[MainExec]
Linux = "QuicBuild"
MacOS = "QuicBuild"
Windows = "QuicBuild.exe"
