AppID = "MabelMedia-LLC.Settings"
ShortDescription = "A Simple Editor Frontend For The SettingsDB Universal Config Value Storage."
LongDescription = ["A Simple Settings Editor For The MabelMedia SettingsDB Format."]
FileBundleHashes = ["8c6b6e64933d21dcfd9acfc993ee5d31c566cfdb1d0cb12fb1399273c0966f17", "1bcda532ed4801147d9be02d1bb07d35f6737f57e9a002ba0c911d714898711e", "ff160cb0db01d1d637fee8bceecfc310760419ef141c1b627e0293cf80642400"]

[Version]
Major = 0
Minor = 0
Patch = 4
BuildNumber = 47

[MainExec]
Linux = "Settings"
MacOS = "Settings"
Windows = "Settings.exe"
