AppID = "MabelMedia-LLC.Settings"
ShortDescription = "A Simple Editor Frontend For The SettingsDB Universal Config Value Storage."
LongDescription = ["A Simple Settings Editor For The MabelMedia SettingsDB Format."]
FileBundleHashes = ["5ff54f5f1224b3b12dc82460ee41960be6efca8aef17d28a04a434c0c32b1039", "d65506db4896d9e03595bd35e04c529d4c0f4a3da1b9aca71835a6741ffc8d31", "44f43890c5e8b4028debd25b85168be45752558c0a6c7047628470ae53695e8a"]

[Version]
Major = 0
Minor = 0
Patch = 1
BuildNumber = 12

[MainExec]
Linux = "Settings"
MacOS = "Settings"
Windows = "Settings.exe"
