AppID = "MabelMedia-LLC.Settings"
ShortDescription = "A Simple Editor Frontend For The SettingsDB Universal Config Value Storage."
LongDescription = ["A Simple Settings Editor For The MabelMedia SettingsDB Format."]
FileBundleHashes = ["603839801bfc021aac11a450c2a4416aa4cc52b4070f3881193e31ad9ea136f6", "d65506db4896d9e03595bd35e04c529d4c0f4a3da1b9aca71835a6741ffc8d31", "98b7caab6da1e73f99accc3ea3ede5fafc2463c68f7052f5facc3958e72a970b"]

[Version]
Major = 0
Minor = 0
Patch = 2
BuildNumber = 23

[MainExec]
Linux = "Settings"
MacOS = "Settings"
Windows = "Settings.exe"
